---
title: "2_train_agnostic_1_notbalanced_1_incid_normal_4olegV2"
output: html_document
date: "2025-10-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##################################################################################
# [NOTE] train test
##################################################################################
# NEWER
# cd /lustre/groups/itg/teams/zeggini/projects/fungen-oa/analyses/olink/classifier/ukbb_3000_oatraits/
# srun --mem=100G -c 10 -p cpu_p   --qos=cpu_preemptible   --time 2-0:0:0 --pty singularity shell -B /home/itg/peter.kreitmaier/container.home.mqq2:/home/itg/peter.kreitmaier/ -B /lustre/groups/itg/ /lustre/groups/itg/shared/containers/worker_3.1.2
# TMPDIR=/lustre/groups/itg/teams/zeggini/users/peter.kreitmaier/tmp R
##################################################################################
```

```{r}
convert_path <- function(original_path) {
  local_path <- gsub("/lustre/groups/itg/teams/zeggini/projects/fungen-oa/analyses/olink/classifier/", 
                     "/home/itg/oleg.vlasovets/projects/protein-benchmark/", 
                     original_path)
  return(local_path)
}

setwd(convert_path("/lustre/groups/itg/teams/zeggini/projects/fungen-oa/analyses/olink/classifier/"))
```

```{r}
base_dir <- "/home/itg/oleg.vlasovets/projects/protein-benchmark/"
dir.create(file.path(base_dir, "output"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(base_dir, "data"), recursive = TRUE, showWarnings = FALSE)
```



```{r}
##################################################################################
# output directories will be:
# /lustre/groups/itg/teams/zeggini/projects/fungen-oa/analyses/olink/classifier/ukbb_3000_oatraits/Spine/5_all_strict_noagesex_more2until5INCID_superc01exclno/models_nrfeat8/models_benchmark_oleg_V1/
# /lustre/groups/itg/teams/zeggini/projects/fungen-oa/analyses/olink/classifier/ukbb_3000_oatraits/Spine/5_all_strict_noagesex_more2until5INCID_superc01exclno/models_nrfeat8/models_comb_benchmark_oleg_V1/
# /lustre/groups/itg/teams/zeggini/projects/fungen-oa/analyses/olink/classifier/ukbb_3000_oatraits/Spine/5_all_strict_noagesex_more2until5INCID_superc01exclno/models_sexagebmi_benchmark_oleg_V1
##################################################################################
start_time <- Sys.time()
##################################################################################
# setwd("/lustre/groups/itg/teams/zeggini/projects/fungen-oa/analyses/olink/classifier/")
setwd("/home/itg/oleg.vlasovets/projects/protein-benchmark/")

##################################################################################
# require("caret")
# require("randomForest")
# require("limma")
# require("data.table")
# require("pROC")
# require("xgboost")
# require("plyr")
# require("glmnet")
# require("doParallel") 
# require("ranger")
# CRAN packages
cran_packages <- c("caret", "randomForest", "data.table", 
                   "pROC", "xgboost", "plyr", "glmnet", "doParallel", "ranger")

# Bioconductor packages
bioc_packages <- c("limma")

# Install CRAN packages
for (pkg in cran_packages) {
    if (!require(pkg, character.only = TRUE)) {
        install.packages(pkg)
        library(pkg, character.only = TRUE)
    }
}

# Install BiocManager if needed
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}

# Install Bioconductor packages
for (pkg in bioc_packages) {
    if (!require(pkg, character.only = TRUE)) {
        BiocManager::install(pkg)
        library(pkg, character.only = TRUE)
    }
}

# Set up parallel processing
cl <- 5
registerDoParallel(cl)
##################################################################################
source("~/projects/protein-benchmark/1_train_agnostic_0_utils.R")

# NOTE: This script requires the following data files from your colleague:
# 1. The utils file: 1_train_agnostic_0_utils.R (already referenced above)
# 2. Protein annotation file: 2941ProteinIDNamesPanels.txt
# 3. Control cohort file: SRplusPC-AllInds-AllVisits-AllCC.ukb9979.v9.txt  
# 4. Sample split files: sample_split_obj_COMBINED_*_split91.rda
# 5. Input data matrices containing protein expression and phenotype data
# The script will create placeholder files but you need real data to run successfully

##################################################################################
# define paths
PATH_OUT_INIT = "/home/itg/oleg.vlasovets/projects/protein-benchmark/output/"
PATH_DATA_DIR = "/home/itg/oleg.vlasovets/projects/protein-benchmark/data/"

get_ctrl_seeds = function(in_number_folds, in_tunelength, in_seed = 123){
    seeds <- vector(mode = "list", length = in_number_folds + 1)
    set.seed(in_seed)
    for(i in 1:in_number_folds) {
        seeds[[i]] <- sample.int(1000, in_tunelength)
    }
    set.seed(in_seed)
    seeds[[in_number_folds + 1]] <- sample.int(1000, 1)

    return(seeds)
}

get_ctrl <- function(in_number_folds, in_tunelength, in_sampling = SAMPLING, in_seed = 13){
    seeds = get_ctrl_seeds(in_number_folds = in_number_folds, in_tunelength = in_tunelength, in_seed = 123)
    
    set.seed(in_seed)
    if(in_sampling != "none"){
        res <- trainControl(method = "cv", number = in_number_folds, verboseIter = T, sampling = in_sampling, 
                    allowParallel = TRUE, seeds=seeds)
    }else{
        res <- trainControl(method = "cv", number = 5, verboseIter = T, seeds=seeds)
    }
    return(res)
}

get_ctrl_repeatedcv <- function(in_number_folds, in_number_repeats, in_tunelength, in_sampling = SAMPLING, in_seed = 13){
    seeds = get_ctrl_seeds(in_number_folds = in_number_folds * in_number_repeats, in_tunelength = in_tunelength, in_seed = 123)
    
    set.seed(in_seed)
    if(in_sampling != "none"){
        res <- trainControl(method = "repeatedcv", number = in_number_folds, verboseIter = T, sampling = in_sampling, 
                    allowParallel = TRUE, seeds=seeds, repeats = in_number_repeats)
    }else{
        res <- NA
    }
    return(res)
}
######################################################
# CHANGE PARAMETERS HERE

#define input and output path
OA_PHENO_VEC = c("Spine")
NR_PROTEINS_VEC = c(8)

length(OA_PHENO_VEC) == length(NR_PROTEINS_VEC)
######################################################
IN_DIR_LABEL <- "more2until5INCID_superc01exclno"
# more2INCID_superc01exclno
######################################################
SUB_DIR = paste0("5_all_strict_noagesex_", IN_DIR_LABEL)

# IN_RELCOL_SUB <- "AOD_diff_case_t0_incid_more2until5","AOD_diff_case_t0_incid_more2"
IN_RELCOL_SUB <- "AOD_diff_case_t0_incid_more2until5"

PERFORM_TRAIN_LIST = list(prot_only = T, sexagebmi = T, comb = T)
PRED_MODE_VEC = c("prot_only", "comb", "sexagebmi")

PRED_COVS = c("sex", "bmi", "age")
PRED_COVS_NOTINCLUDE = setdiff(c("sex", "age", "bmi"), PRED_COVS)
######################################################
adjust_comb_nrprots = T

PERFORM_RFE = T

TRAIN_FI_RF_GRID = T

TRAIN_FI_RF_NR_ITER = 5
TRAIN_FI_RF_NR_FOLD = 5

NR_FOLDS_FEATURESEL_RF = 5

SAMPLING = "rose"

VAL_RF = T
VAL_GLMNET = T
VAL_XG = T

TUNELENGTH_RF = 10
TUNELENGTH_GLMNET = 80
TUNELENGTH_XG = 10

#PRED_MODE_VEC = c("prot_only", "comb", "sexagebmi")


# define label of outcome files
if(PERFORM_RFE){
    label_rfe = "rfe"
}else{
    label_rfe = "norfe"
}

PATH_ANNO = paste0(PATH_DATA_DIR, "2941ProteinIDNamesPanels.txt")
PATH_CC = paste0(PATH_DATA_DIR, "SRplusPC-AllInds-AllVisits-AllCC.ukb9979.v9.txt")

# Create output and data directories
dir.create(PATH_OUT_INIT, recursive = TRUE, showWarnings = FALSE)
dir.create(PATH_DATA_DIR, recursive = TRUE, showWarnings = FALSE)
#PATH_SAMPLES_CC_FILE = "/lustre/groups/itg/teams/zeggini/projects/fungen-oa/analyses/olink/classifier/ukbb_3000_oatraits/IN_OA_ALL_DATES_diff_case_WITHCOMBINED_until2PREVINCID_V9.rda"
##################################################################################
# [ITER] iterate over phenotypes and nr of proteins
# curr_elem = 1
sapply(1:length(OA_PHENO_VEC), FUN = function(curr_elem){

    OA_PHENO = OA_PHENO_VEC[curr_elem]
    NR_PROTEINS = NR_PROTEINS_VEC[curr_elem]

    # set_paths
    PATH_IN = paste0(PATH_OUT_INIT, OA_PHENO, "/", SUB_DIR,"/")
    PATH_IN_SUBDIR = paste0("models_nrfeat", NR_PROTEINS)

    PATH_IN_ORIG = PATH_IN
    PATH_IN = paste0(PATH_IN, PATH_IN_SUBDIR)


    # SET THESE DIRECOTIRES TO BENCHMARK FOLDERS
    # PATH_OUT_MODEL_PONLY = paste0(PATH_IN, "/models_benchmark_peter_V1/")
    # PATH_OUT_MODEL_COMB = paste0(PATH_IN, "/models_comb_benchmark_peter_V1/")
    # PATH_OUT_MODEL_sexagebmi = paste0(PATH_IN_ORIG, "/models_sexagebmi_benchmark_peter_V1/")

    PATH_OUT_MODEL_PONLY = paste0(PATH_IN, "/models_benchmark_oleg_V1/")
    PATH_OUT_MODEL_COMB = paste0(PATH_IN, "/models_comb_benchmark_oleg_V1/")
    PATH_OUT_MODEL_sexagebmi = paste0(PATH_IN_ORIG, "/models_sexagebmi_benchmark_oleg_V1/")

    PATH_OUT_TMPFILES_PONLY = paste0(PATH_OUT_MODEL_PONLY, "/tmp_files/")
    PATH_OUT_TMPFILES_COMB = paste0(PATH_OUT_MODEL_COMB, "/tmp_files/")
    PATH_OUT_TMPFILES_sexagebmi = paste0(PATH_OUT_MODEL_sexagebmi, "/tmp_files/")

    # create model and tmp_files (if not there)

    dir.create(PATH_IN, recursive = TRUE, showWarnings = FALSE) 

    dir.create(PATH_OUT_MODEL_PONLY, recursive = TRUE, showWarnings = FALSE) 
    dir.create(PATH_OUT_MODEL_COMB, recursive = TRUE, showWarnings = FALSE) 
    dir.create(PATH_OUT_MODEL_sexagebmi, recursive = TRUE, showWarnings = FALSE) 

    dir.create(PATH_OUT_TMPFILES_PONLY, recursive = TRUE, showWarnings = FALSE) 
    dir.create(PATH_OUT_TMPFILES_COMB, recursive = TRUE, showWarnings = FALSE) 
    dir.create(PATH_OUT_TMPFILES_sexagebmi, recursive = TRUE, showWarnings = FALSE) 

    p_anno = get_p_anno(in_p = PATH_ANNO)

    NR_PROTEINS_COMB = NR_PROTEINS + 1
    ##################################################################################
    # PRED_MODE = PRED_MODE_VEC[1]
    # prot_only|sexagebmi|comb
    ####################################################################################################################################################################
    sapply(PRED_MODE_VEC, FUN = function(PRED_MODE){
        ##################################################################################
        print("########################################################################################")
        print(PRED_MODE)
        print("########################################################################################")
        PERFORM_TRAIN = PERFORM_TRAIN_LIST[[PRED_MODE]]
        ##################################################################################
        # define current mode and tmpfile
        if(PRED_MODE == "prot_only"){
            PATH_OUT_MODEL = PATH_OUT_MODEL_PONLY
            PATH_OUT_TMPFILES = PATH_OUT_TMPFILES_PONLY
        }else if(PRED_MODE == "sexagebmi"){
            PATH_OUT_MODEL = PATH_OUT_MODEL_sexagebmi
            PATH_OUT_TMPFILES = PATH_OUT_TMPFILES_sexagebmi
        }else if(PRED_MODE == "comb"){
            PATH_OUT_MODEL = PATH_OUT_MODEL_COMB
            PATH_OUT_TMPFILES = PATH_OUT_TMPFILES_COMB
        }else{
            stop("No valid mode. set parameter to: prot_only or sexagebmi or comb")
        }

        # lsit of covariates that are potentially used as predictors
        if(PRED_MODE != "sexagebmi"){
            OUT_LABEL = paste0(SAMPLING, "_", "top", NR_PROTEINS, "_", label_rfe)
        }else{
            OUT_LABEL = paste0(SAMPLING, "_", PRED_MODE)
        }
        # /lustre/groups/itg/teams/zeggini/projects/fungen-oa/analyses/olink/classifier/ukbb_3000_oatraits//TKR/2_all_strict/models_nrfeat30/models/
        ##################################################################################
        # load input data (traintest/validation) for proteins and pheno
        # Check if required functions exist
        if (!exists("get_matrices")) {
            stop("ERROR: get_matrices function not found. Please ensure 1_train_agnostic_0_utils.R is properly sourced and contains all required functions.")
        }
        
        # Check if sample split file exists
        sample_split_file <- paste0(PATH_DATA_DIR, "sample_split_obj_COMBINED_", IN_DIR_LABEL, "_split91.rda")
        if (!file.exists(sample_split_file)) {
            stop("ERROR: Sample split file not found: ", sample_split_file, "\nPlease obtain this file from your colleague.")
        }
        
        get_matrices_obj = get_matrices(in_path_cc = PATH_CC, in_relcol_sub = IN_RELCOL_SUB, in_outcome = OA_PHENO, 
                                    in_path_sample_split = sample_split_file, 
                                    in_pred_mode = PRED_MODE)

        p_mtx_traintest_ukbb = get_matrices_obj$p_mtx_traintest
        pheno_train_test_ukbb = get_matrices_obj$pheno_train_test

        p_mtx_val_ukbb = get_matrices_obj$p_mtx_val
        pheno_val_ukbb = get_matrices_obj$pheno_val

        rm(get_matrices_obj)
        ##################################################################################
        # load input data (all); used for pwas
        # get_matrices_obj = get_matrices_allsamples(
        #     in_path_datalist = paste0(PATH_OUT_INIT,  "data_list_controlfromcontrolcolumn_COMBINED_", IN_DIR_LABEL, "_V9.rda"), 
        #                     in_relcol_sub = IN_RELCOL_SUB, is_bmi_used = (PRED_MODE != "prot_only"),oa_pheno_here = OA_PHENO, path_cc_here = PATH_CC)

        # pheno_all = get_matrices_obj$pheno_all
        # p_mtx_all = get_matrices_obj$p_mtx_all
        # identical(rownames(pheno_all), rownames(p_mtx_all))

        # rm(get_matrices_obj)
        ##################################################################################
        # PERFORM PWAS (in train test)
        if((PRED_MODE != "sexagebmi")){
            prot_sig = perform_pwas(in_p_mtx = p_mtx_traintest_ukbb[,!(colnames(p_mtx_traintest_ukbb) %in% PRED_COVS)], in_pheno = pheno_train_test_ukbb)
            tmp = prot_sig$pwas_sumstats
            save(tmp, file = paste0(PATH_OUT_MODEL, "pwas.rda"))
            rm(tmp)
            prot_sig = prot_sig$prot_sig

            # force inclusion of bmi, age and sex as predictors
            if((PRED_MODE != "prot_only")){
                prot_sig = c(prot_sig, PRED_COVS)
            }
        }
        ####################################################################################################################
        ####################################################################################################################
        # [HELPER] perform training testing
        # NOTE: 
        if((PRED_MODE != "sexagebmi")){
            if(PERFORM_TRAIN){
                ####################################################################################################################
                # clean tmp folder
                # clean_tmp_train_folder(in_p = PATH_OUT_TMPFILES)
                ####################################################################################################################
                # define data for script below
                p_in = pheno_train_test_ukbb
                m_in = p_mtx_traintest_ukbb[, prot_sig]
                ####################################################################################################################
                print(paste0(" --> train data samples in right order: ", identical(rownames(p_in), rownames(m_in))))
                print(paste0(" --> nr considered proteins: ", length(unique(colnames(m_in)))))
                ####################################################################################################################
                # define mtry around default value (sqrt(number features)); https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6198850/ --> corrected impurity is good
                tuneGrid = define_train_grid(nr_feat = length(prot_sig), rel_row = NULL) 

                ctrl = get_ctrl(in_number_folds = NR_FOLDS_FEATURESEL_RF, in_tunelength = nrow(tuneGrid), 
                                in_sampling = SAMPLING)
                ####################################################################################################################
                # print(paste0("class of ctrl: ", ctrl))
                training_obj = perform_rf_training(in_number_iter = TRAIN_FI_RF_NR_ITER, 
                                in_number_folds = TRAIN_FI_RF_NR_ITER, m_in = m_in, 
                             p_in = p_in, in_ctrl = ctrl, in_grid = tuneGrid, outpath = PATH_OUT_TMPFILES)
                ##################################################################################            
            }
            ##################################################################################
            print(get_sen_spec_acc(in_p = PATH_OUT_TMPFILES))
            ##################################################################################
            # [OPTION 1]
            prot_mean = get_feat_importance(in_p = PATH_OUT_TMPFILES, in_mtx = t(p_mtx_traintest_ukbb[,prot_sig]), 
                        in_p_anno = get_p_anno(in_p = PATH_ANNO))
            print(paste0(cor.test(prot_mean$imp_mean, prot_mean$imp_median, method = "pearson")))

            # load pwas, merge in importance and write it out again
            tmp = get(load(file = paste0(PATH_OUT_MODEL, "pwas.rda")))
            prot_mean = cbind(prot_mean, tmp[rownames(prot_mean),])
            fwrite(prot_mean, file = paste0(PATH_OUT_MODEL, "pwas_nrfeat_", OUT_LABEL, ".txt.gz"), sep = "\t", compress = "gzip")
            # prot_mean = fread(file = paste0(PATH_OUT_MODEL, "pwas_nrfeat_", OUT_LABEL, ".txt.gz"), sep = "\t")

            # PLOT
            pdf(file = paste0(PATH_OUT_MODEL, "prot_importance_mean_CLEAN_", OUT_LABEL, ".pdf"), onefile = T)
            ggplot(prot_mean, aes(x=rank, y=imp_mean, color = "black")) + geom_point(show.legend = FALSE) + theme_light() +
                ylab("Mean feature\nimportance") + xlab("Proteins")
            ggplot(prot_mean[1:30,], aes(x=rank, y=imp_mean, color = "black")) + geom_point(show.legend = FALSE) + theme_light() +
                ylab("Mean feature\nimportance") + xlab("Proteins") 
            dev.off()
        }
        ###################################################################################################################
        # CHOSE FEATURES --> output: rel_features
        ##################################################################################
        # PRED_MODE --> prot_only|sexagebmi|comb
        if(PRED_MODE == "prot_only"){
            if(PERFORM_RFE){


                #in_pheno = pheno_train_test_ukbb
                #in_m = p_mtx_traintest_ukbb
                #in_dat = prot_mean
                #in_nr_proteins = NR_PROTEINS
                #rfe_number = 5
                #in_label = OUT_LABEL
                #in_p = PATH_OUT_MODEL


                # perform rfe 
                registerDoParallel(5)
                rel_features = run_rfe(in_pheno = pheno_train_test_ukbb, in_m = p_mtx_traintest_ukbb, in_dat = prot_mean, in_nr_proteins = NR_PROTEINS, 
                                            rfe_number = 5, in_label = OUT_LABEL, in_p = PATH_OUT_MODEL)
                
                # adjust label
                OUT_LABEL = rel_features$in_label

                # grep features
                rel_features = rel_features$rel_features
            }else{
                # grep features
                rel_features = getfrom_ranked_proteins()
            }
        }

        if(PRED_MODE == "sexagebmi"){
                rel_features = PRED_COVS
        }

        if(PRED_MODE == "comb"){
            if(PERFORM_RFE){
                # perform rfe (rfe potentially with age sex and bmi; if not, inclusion forced later.....; due to presence of age, sex and bmi, prot set of comb and prot_only 
                # can be different)

                # perform rfe for some comb cases
                if(adjust_comb_nrprots){
                    rfe_nr_prots = NR_PROTEINS_COMB
                }else{
                    rfe_nr_prots = NR_PROTEINS
                }


                registerDoParallel(5)

                # to be safe that "comb" does not include age, sex or bmi if they are not supposed to be there
                prot_mean = prot_mean[!(rownames(prot_mean) %in% PRED_COVS_NOTINCLUDE),]

                rel_features = run_rfe(in_pheno = pheno_train_test_ukbb, in_m = p_mtx_traintest_ukbb, in_dat = prot_mean, 
                    in_nr_proteins = rfe_nr_prots, rfe_number = 5, 
                    in_label = OUT_LABEL, in_p = PATH_OUT_MODEL)
                # rel_features = get(load(file = paste0(PATH_OUT_MODEL, "res_obj_feat.rda")))
                
                # adjust label
                OUT_LABEL = rel_features$in_label

                # grep features
                rel_features = rel_features$rel_features

                # force inclusion of sex, age and bmi
                rel_features = unique(c(rel_features, PRED_COVS))
            }else{
                # grep features
                rel_features = getfrom_ranked_proteins()

                # force inclusion of sex, age and bmi
                rel_features = unique(c(rel_features, PRED_COVS))
            }
        }
        ##################################################################################
        train_d = p_mtx_traintest_ukbb[,rel_features]
        dim(train_d)
        #  45541    50

        all(rel_features %in% colnames(train_d)) # T
        table(pheno_train_test_ukbb$oa_status)

        # make sure pheno and data matrix are in same order
        #identical(rownames(train_d), rownames(pheno_train_test_ukbb)) # T
        ##################################################################################
        if(VAL_RF){
            print("Training RF")
            # build a random forest model
            # define mtry around default value (sqrt(number features)); https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6198850/ --> corrected impurity is good
            mtry = ceiling(sqrt(ncol(train_d)))
            mtry = unique(ceiling(c(mtry*0.6, mtry*0.8, mtry*1, mtry*1.2)))

            tuneGrid = data.frame(mtry = mtry, min.node.size = 1, splitrule = "gini")
            #  mtry min.node.size splitrule
            #1    5             1      gini
            #2    7             1      gini
            #3    8             1      gini
            #4   10             1      gini
            tuneGrid = data.frame(mtry = tuneGrid[, c("mtry")])

            TUNELENGTH_RF = nrow(tuneGrid)
            RF_MODEL_LABEL = paste0("model_rf_", OUT_LABEL, "_tunegrid", TUNELENGTH_RF , ".rda")

            log_file = paste0(strsplit(basename(RF_MODEL_LABEL), "\\.")[[1]][1], ".log")
            file.remove(paste0(PATH_OUT_MODEL, log_file))
            write_log_file(in_pheno_tt = pheno_train_test_ukbb, in_pheno_val = pheno_val_ukbb, 
                            in_feat = rel_features, in_log_file = log_file, in_prot_mean = prot_mean, 
                            in_dir = PATH_OUT_MODEL, in_pred_mode = PRED_MODE)

            ctrl = get_ctrl_repeatedcv(in_number_folds = NR_FOLDS_FEATURESEL_RF, 
                                    in_number_repeats = 5, 
                                    in_tunelength = nrow(tuneGrid), 
                                    in_sampling = SAMPLING, in_seed = 13)

            set.seed(13)
            model_rf <- caret::train(y = pheno_train_test_ukbb$oa_status, 
                                    # x = train_d, method = "ranger", 
                                    x = train_d, method = "rf", 
                                    preProcess = NULL, trControl = ctrl, metric = "Accuracy", 
                                    maximize = T, tuneGrid = tuneGrid)

            save(model_rf, file = paste0(PATH_OUT_MODEL, RF_MODEL_LABEL))   
            # /lustre/groups/itg/teams/zeggini/projects/fungen-oa/analyses/olink/classifier/ukbb_3000_oatraits//Combined_TKRKnee/2_all_strict//modelsV2/model_rf_rose_top50_norfe.rda
        }
        #/lustre/groups/itg/teams/zeggini/projects/fungen-oa/analyses/olink/classifier/ukbb_3000_oatraits//Knee/2_all_strict/models_nrfeat30/models/
        ##################################################################################
        # build an elastic net
        if(VAL_GLMNET){
            print("Training GLMNET")
            identical(rownames(train_d), rownames(pheno_train_test_ukbb)) # T

            GLMNET_MODEL_LABEL = paste0(PATH_OUT_MODEL, "model_glmnet_", OUT_LABEL, "_tunegrid", TUNELENGTH_GLMNET , ".rda")

            log_file = paste0(strsplit(basename(GLMNET_MODEL_LABEL), "\\.")[[1]][1], ".log")
            file.remove(paste0(PATH_OUT_MODEL, log_file))
            write_log_file(in_pheno_tt = pheno_train_test_ukbb, in_pheno_val = pheno_val_ukbb, in_feat = rel_features, in_log_file = log_file, in_prot_mean = prot_mean, 
                        in_dir = PATH_OUT_MODEL, in_pred_mode = PRED_MODE)

            ctrl = get_ctrl_repeatedcv(in_number_folds = NR_FOLDS_FEATURESEL_RF, 
                                    in_number_repeats = 5, 
                                    in_tunelength = TUNELENGTH_GLMNET, 
                                    in_sampling = SAMPLING, in_seed = 13)

            set.seed(13)
            model_glmnet <- caret::train(y = pheno_train_test_ukbb$oa_status, x = train_d, 
                                            method = "glmnet", preProcess = NULL, 
                                            trControl = ctrl, metric = "Accuracy", maximize = T, 
                                            tuneLength = TUNELENGTH_GLMNET, 
                                            importance  = "impurity_corrected")

            
            save(model_glmnet, file = paste0(PATH_OUT_MODEL, basename(GLMNET_MODEL_LABEL)))    
        }
        ##################################################################################
        if(VAL_XG){
            print("Training XG")
            registerDoParallel(1)

            # build complicated xgboost model; this is an advenced ensembl technique
            # this tutorial: https://odsc.medium.com/getting-up-to-speed-with-xgboost-in-r-ffbe402263f5
            identical(rownames(train_d), rownames(pheno_train_test_ukbb)) # T

            XG_MODEL_LABEL = paste0(PATH_OUT_MODEL, "model_xgboost_", OUT_LABEL, "_tunegrid", TUNELENGTH_XG , ".rda")

            log_file = paste0(strsplit(basename(XG_MODEL_LABEL), "\\.")[[1]][1], ".log")
            file.remove(paste0(PATH_OUT_MODEL, log_file))
            write_log_file(in_pheno_tt = pheno_train_test_ukbb, in_pheno_val = pheno_val_ukbb, in_feat = rel_features, in_log_file = log_file, in_prot_mean = prot_mean, 
                        in_dir = PATH_OUT_MODEL, in_pred_mode = PRED_MODE)
            ###################################
            set.seed(13)
            grid_50 <- expand.grid(
                nrounds = c(150, 300, 500),
                max_depth = c(1,3,5,7,10),
                eta = c(0.03, 0.05, 0.1),
                gamma = c(0),
                colsample_bytree = 1.0,
                min_child_weight = c(1, 3),
                subsample = c(0.6,0.8, 1.0))   

            ctrl = get_ctrl_repeatedcv(in_number_folds = NR_FOLDS_FEATURESEL_RF, 
                                    in_number_repeats = 5, 
                                    in_tunelength = nrow(grid_50), 
                                    in_sampling = SAMPLING, in_seed = 13)
            ###################################
            set.seed(13)
            model_xgboost <- caret::train(y = pheno_train_test_ukbb$oa_status, x = train_d, 
                                            method = "xgbTree", preProcess = NULL, 
                                            trControl = ctrl, metric = "Accuracy", maximize = T, 
                                            tuneGrid = grid_50, verbosity = 0)

            
            save(model_xgboost, file = paste0(PATH_OUT_MODEL, basename(XG_MODEL_LABEL)))                                       
            # Selecting tuning parameters Fitting nrounds = 200, max_depth = 2, eta = 0.3, gamma = 0, 
            # colsample_bytree = 0.8, min_child_weight = 1, 
            # subsample = 0.875 on full training set
        }
        return(T)
    })
})
end_time <- Sys.time()
end_time - start_time
# Time difference of 2.06447 hours
####################################################################################################################################################################
```

